const wordsObject = {

    animais: ['GATO', 'CACHORRO', 'CAVALO', 'LOBO', 'COBRA', 'RATO', 'TATU', 'ANTA', 'ENGUIA',
    'JACARE', 'ESQUILO', 'TARTARUGA', 'PEIXE', 'ZEBRA', 'ORNITORRINCO', 'COELHO', 'LONTRA', 'ALCE', 'FORMIGA',
    'ARANHA', 'LULA', 'POLVO', 'AGUIA', 'CORUJA', 'MINHOCA', 'LESMA', 'URSO', 'CARANGUEIJO', 'VEADO', 'BUFALO', 'PUMA',
    'JAGUATIRICA', 'ELEFANTE', 'GIRAFA', 'GALINHA', 'GALO', 'CROCODILO'],

    cidades: ['LONDRES', 'PARIS', 'BANGKOK', 'CINGAPURA', 'HONG KONG', 'MADRI', 'ISTAMBUL', 'FRANKFURT',
    'DUBAI', 'ROMA', 'SEUL', 'NOVA YORK', 'BARCELONA', 'VIENA', 'XANGAI', 'ROMA', 'MIAMI', 'PRAGA', 'MECA', 'BERLIM',
    'BRUXELAS', 'VENEZA', 'MOSCOU', 'ATENAS', 'PEQUIM', 'CAIRO', 'KYOTO', 'ESTOCOLMO', 'CARACAS', 'RIO DE JANEIRO', 'ORLANDO',
     'LAS VEGAS'],

    comidas: ['SUSHI', 'BATATA FRITA', 'HAMBURGUER', 'ARROZ', 'BATATA', 'PIZZA', 'COXINHA', 'CACHORRO QUENTE', 'PASTEL', 'TORRADA',
    'SALGADINHO', 'CHOCOLATE', 'BANANA', 'PERA', 'BOLO', 'REFRIGERANTE', 'SUCO', 'VINHO', 'MANTEIGA', 'MARGARINA', 'OVO',
    'FARINHA', 'LEITE', 'TEMAKI', 'GOIABA', 'ABACATE', 'ABACAXI', 'PITANGA', 'ACEROLA', 'AMEIXA', 'AMORA', 'BACON', 'AZEITE'],

    jogos: ['FIFA', 'FORTNITE', 'MINECRAFT', 'MIST', 'HALO', 'TEAM FORTRESS', 'FREE FIRE', 'MARIO', 'METAL GEAR', 'DONKEY KONG',
    'DOOM', 'BATMAN ARKHAN', 'BIOSHOCK', 'FINAL FANTASY', 'PORTAL', 'DEUS EX', 'STARCRAFT', 'POKEMON', 'DARK SOULS', 'RESIDENT EVIL',
    'DIABLO', 'THE SIMS', 'FALLOUT', 'FAR CRY', 'MORTAL KOMBAT', 'BATTLEFIELD', 'GOD OF WAR', 'HEARTHSTONE', 'DRAGON CITY', 'PAC MAN', 'CALL OF DUTY'],

    eletro: ['TECLADO', 'MOUSE', 'MONITOR', 'COMPUTADOR', 'GELADEIRA', 'CELULAR', 'TABLET', 'NOTEBOOK', 'ASPIRADOR', 'TORRADEIRA',
    'VIDEO GAMES', 'CARROS', 'CAFETEIRA', 'BATEDEIRA', 'LIQUIDIFICADOR', 'AQUECEDOR', 'LAVADORA', 'CAIXA DE SOM', 'MICROFONE',
    'FONE DE OUVIDO', 'LEITOR DE DVD', 'DESPERTADOR', 'ABAJUR', 'VENTILADOR', 'IMPRESSORA', 'SECADORA'],

    esportes: ['ATLETISMO', 'BEISEBOL', 'BOXE', 'CICLISMO', 'CANOAGEM', 'ESGRIMA', 'FUTEBOL', 'GOLFE', 'JUDO', 'HIPISMO',
    'ARCO E FLECHA' , 'VOLEI', 'TRIATO', 'RUGBI', 'BASQUETE', 'SURFE', 'VELA', 'HANDEBOL', 'SKATE', 'CAPOEIRA', 'FUTSAL', 'ESQUI',
    'CORRIDA', 'XADREZ', 'MARATONA', 'ATLETAS', 'JIU JITSU', 'FUTVOLEI', 'TAEKWONDO'],

    pokemons: ['MAGNEMITE', 'SPOINK', 'ZEKROM', 'SENTRET', 'FERALIGATR', 'AMPHAROS', 'SABLEYE', 'DUGTRIO', 'HELIOPTILE', 'KABUTO',
    'CATERPIE', 'PURRLOIN', 'UMBREON', 'EEVEE', 'SANDSLASH', 'AMAURA', 'CACNEA', 'AZUMARILL', 'LAPRAS', 'BOLDORE', 'CASTFORM', 'MEDITITE',
    'HAUNTER', 'BELDUM', 'FENNEKIN', 'SNIVY', 'BUTTERFREE', 'JOLTEON', 'HORSEA', 'YANMEGA', 'TYPHLOSION', 'AZURILL', 'RELICANTH', 'PONYTA',
    'RAPIDASH', 'METAGROSS', 'MARILL', 'ELECTRODE', 'VOLTORB', 'ELECTRIKE', 'CUBONE', 'NINCADA', 'SPEAROW', 'SCRAGGY', 'PIDGEY', 'RALTS'],

    geral: ['LONDRES', 'PARIS', 'BANGKOK', 'CINGAPURA', 'HONG KONG', 'MADRI', 'ISTAMBUL', 'FRANKFURT',
    'DUBAI', 'ROMA', 'SEUL', 'NOVA YORK', 'BARCELONA', 'VIENA', 'XANGAI', 'ROMA', 'MIAMI', 'PRAGA', 'MECA', 'BERLIM',
    'BRUXELAS', 'VENEZA', 'ORLANDO', 'MOSCOU', 'ATENAS', 'PEQUIM', 'CAIRO', 'KYOTO', 'ESTOCOLMO', 'CARACAS', 'GATO',
    'CACHORRO', 'CAVALO', 'LOBO', 'COBRA', 'RATO', 'TATU', 'ANTA', 'ENGUIA',
    'JACARE', 'ESQUILO', 'TARTARUGA', 'PEIXE', 'ZEBRA', 'ORNITORRINCO', 'COELHO', 'LONTRA', 'ALCE', 'FORMIGA',
    'ARANHA', 'LULA', 'POLVO', 'AGUIA', 'CORUJA', 'MINHOCA', 'LESMA', 'URSO', 'CARANGUEIJO', 'VEADO', 'BUFALO',
    'FIFA', 'FORTNITE', 'MINECRAFT', 'MIST', 'HALO', 'TEAM FORTRESS', 'FREE FIRE', 'MARIO', 'METAL GEAR', 'DONKEY KONG',
    'DOOM', 'BATMAN ARKHAN', 'BIOSHOCK', 'FINAL FANTASY', 'PORTAL', 'DEUS EX', 'STARCRAFT', 'POKEMON', 'DARK SOULS', 'RESIDENT EVIL',
    'DIABLO', 'THE SIMS', 'FALLOUT', 'FAR CRY', 'MORTAL KOMBAT', 'BATTLEFIELD', 'GOD OF WAR', 'HEARTHSTONE', 'DRAGON CITY',
    'ATLETISMO', 'BEISEBOL', 'BOXE', 'CICLISMO', 'CANOAGEM', 'ESGRIMA', 'FUTEBOL', 'GOLFE', 'JUDO', 'HIPISMO',
    'ARCO E FLECHA' , 'VOLEI', 'TRIATO', 'RUGBI', 'BASQUETE', 'SURFE', 'VELA', 'HANDEBOL', 'SKATE', 'CAPOEIRA', 'FUTSAL', 'ESQUI',
    'CORRIDA', 'XADREZ', 'MARATONA', 'ATLETAS', 'MAGNEMITE', 'SPOINK', 'ZEKROM', 'SENTRET', 'FERALIGATR', 'AMPHAROS', 'SABLEYE', 'DUGTRIO', 'HELIOPTILE', 'KABUTO',
    'CATERPIE', 'PURRLOIN', 'UMBREON', 'EEVEE', 'SANDSLASH', 'AMAURA', 'CACNEA', 'AZUMARILL', 'LAPRAS', 'BOLDORE', 'CASTFORM', 'MEDITITE',
    'HAUNTER', 'BELDUM', 'FENNEKIN', 'SNIVY', 'BUTTERFREE', 'JOLTEON', 'HORSEA', 'YANMEGA', 'TYPHLOSION', 'AZURILL', 'RELICANTH', 'PONYTA',
    'RAPIDASH', 'METAGROSS', 'MARILL', 'ELECTRODE', 'VOLTORB', 'ELECTRIKE', 'CUBONE', 'NINCADA', 'SPEAROW', 'SCRAGGY', 'PIDGEY', 'RALTS',
    'SUSHI', 'BATATA FRITA', 'HAMBURGUER', 'ARROZ', 'BATATA', 'PIZZA', 'COXINHA', 'CACHORRO QUENTE', 'PASTEL', 'TORRADA',
    'SALGADINHO', 'CHOCOLATE', 'BANANA', 'PERA', 'BOLO', 'REFRIGERANTE', 'SUCO', 'VINHO', 'MANTEIGA', 'MARGARINA', 'OVO',
    'FARINHA', 'LEITE', 'TEMAKI', 'GOIABA', 'ABACATE', 'ABACAXI', 'PITANGA', 'ACEROLA', 'AMEIXA', 'AMORA', 'BACON',
    'TECLADO', 'MOUSE', 'MONITOR', 'COMPUTADOR', 'GELADEIRA', 'CELULAR', 'TABLET', 'NOTEBOOK', 'ASPIRADOR', 'TORRADEIRA',
    'VIDEO GAMES', 'CARROS', 'CAFETEIRA', 'BATEDEIRA', 'LIQUIDIFICADOR', 'AQUECEDOR', 'LAVADORA', 'CAIXA DE SOM', 'MICROFONE',
    'FONE DE OUVIDO', 'LEITOR DE DVD', 'DESPERTADOR', 'ABAJUR', 'VENTILADOR', 'AR CONDICIONADO', 'IMPRESSORA', 'SECADORA', 'PUMA', 'JAGUATIRICA', 'ELEFANTE', 'GALINHA', 
    'GALO', 'RIO DE JANEIRO', 'PAC MAN', 'LAS VEGAS', 'AZEITE', 'CROCODILO', 'JIU JITSU', 'FUTVOLEI', 'TAEKWONDO'] 

}

export default function generateRandomWord(categ) {

    const WordsArray = wordsObject[categ];

    const randomWord = WordsArray[ Math.floor( Math.random() * WordsArray.length ) ]

    return randomWord

}
